### ISSUE TITLE
How Do I Search By Tag?

### ISSUE THREAD

**Issue by jfelchner** [ctrlpvim/ctrlp.vim#102]
I added `tag` to the ctrlp extensions and I see it in the prompt, but for regex and filename I can press `<C-R>` and `<C-D>` respectively, but I looked all over in the docs and I can't find how to switch to tag mode.

I also looked at the default list of key mappings and I don't see it in there either.

**Comment by tacahiroy** [comment]
Have you tried `:CtrlPBufTag` and / or `:CtrlPBufTagAll`? Or what you want to do is different to these built-in extension doing I guess.

**Comment by jfelchner** [comment]
@tacahiroy yeah those work and I can bind them to a mapping, but CtrlP has built in keys to switch modes while the window is up.  I want that same thing for the tag extension.  So that I can switch modes while the window is open.

**Comment by mattn** [comment]
See `:help ctrlp-extensions`

**Comment by jfelchner** [comment]
@mattn I looked there.  I'll look again.

**Comment by jfelchner** [comment]
@mattn finally got it.  Thanks!

**Comment by jfelchner** [comment]
For those coming after me.  It's not exactly clear in the docs, but `<C-f>` cycles through all modes in the window.  When you enable an extension it adds that mode so simply repeatedly pressing `<C-f>` will eventually get you to what you want.

**Comment by alphaCTzo7G** [comment]
@jfelchner, is there a way to directly search tags.. I know there is a `:CtrlPTag`. You also mentioned that there is a `:CtrlPBufTag` and / or `:CtrlPBufTagAll`. What is the difference between these options?

Further, I found the tag search to be a bit slow, perhaps because the tag search is also using the `VIM` engine. 

Is it possible to use `grep` or some other way to search through the tags for faster tag search?
