### ISSUE TITLE
Forced to use Ctrl+Shift+P instead of Ctrl+P

### ISSUE THREAD

**Issue by AdrienGiboire** [ctrlpvim/ctrlp.vim#414]
For a few days now, I need to press `Ctrl + Shift + P` to trigger ctrlp. I changed nothing configuration wise. It used to work with only `Ctrl + P`.

Even forcing it doesn't do a thing:

```
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
```

or

```
noremap <C-p> :CtrlP<CR>
```

The `map` command feedback:

```
:map <c-p>
   <C-P>         <Plug>(ctrlp)
```

Some hints of what I could have missed?

**Comment by mattn** [comment]
You can't map CTRL+SHIFT+P in vim. (not a issue of CtrlP)

**Comment by AdrienGiboire** [comment]
You got me wrong. I'm saying I *have to* do this to trigger CtrlP instead of the use CTRL+P and I can't figure out why all of a sudden.

**Comment by mattn** [comment]
It's not an issue of vim and ctrlp. maybe it is an issue of your terminal.

**Comment by mattn** [comment]
FYI: This is a reason why I can say that it is not an issue of vim and ctrlp. Because terminal and vim cannot recognize SHIFT+CTRL pressing. Genraral terminal doesn't have feature that can cat keys CTRL-SHIFT both and some key. SHIFT key code on terminal is asigned to decrement 0x20. For example, `a` is 0x61 and `A` is 0x41. And CTRL key code is asigned to decrement 0x40.  So `CTRL-a` is 0x01. You can understand why `CTRL-h` is 0x08 since `H` is 0x48.

**Comment by AdrienGiboire** [comment]
I get it, you're right. Thanks for the explanations. #til :)

I went through everything and it was an issue with vim + tmux

Thanks for your time and patience :)
